### ISSUE TITLE
Mapa não aparece

### ISSUE THREAD

**Issue by tamielbr** [oeco/jeo#11]
Fiz uma nova instalação do Mappress (0.78) em WP (3.5.1) hospedado em servidor compartilhado. Criei novo mapa, e coloquei dois posts com georeferenciamento. Mas nada aprece na página principal. Tentei browsers diferentes e usar Google Maps ou Open Street.
Mapa em: http://educacaoaberta.org/map. Valeu!

**Comment by miguelpeixe** [comment]
@tamielbr 

Você definiu o mapa criado como principal em Mappress Settings? Caso não, tente fazer isso e poste os resultados.

Abraços

**Comment by tamielbr** [comment]
Sim. Está como "Mapa destacado com últimos posts", e em "Mapa destacado", o mapa foi escolhido. Estou usando "OpenStreetMaps com Nominatim". Fora isso, nada demais. Alguma outra sugestão ou requerimento de sistema? Valeu!

**Comment by miguelpeixe** [comment]
A visualização do mapa está retornando erro 500, ou seja, erro de PHP. Tente baixar a última versão novamente e caso persista, consegue me enviar o error_log do seu PHP?

**Comment by tamielbr** [comment]
Fiz uma instalação limpa novamente, baixei a última versão daqui e WP 3.5.1. Criei um mapa, e adicionei um ponto (www.educacaoaberta.org/press). O que aparece relativo ao Mappress no PHP log tá aqui (aparece repetidamente):

[13-Jun-2013 20:38:19 UTC] PHP Fatal error:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required '/home/educacaoaberta/www/mappress/wp-load.php' (include_path='.:/usr/local/lib/php') in /home/educacaoaberta/www/mappress/wp-blog-header.php on line 12

valeu!

**Comment by diraol** [comment]
Estou tendo um problema muito similar, mas sem o erro 500.
Se eu clico em "criar novo mapa" e publico, o mapa aprece ok (http://mappress.estadaodados.com/?map=teste-2). Porém, se eu tendo usar algum mapa que eu criei no mapbox ele não funciona (http://mappress.estadaodados.com/?map=primeiro-teste). Este segundo mapa eu tentei usar esse aqui:
http://a.tiles.mapbox.com/v3/estadaodados.reservatorios/page.html#7.00/-19.441/-46.165
Usando como "ID" na configuração do post "_estadaodados.reservatorios_", mas não deu certo.

Tenho a impressão que é dificuldade em acessar o tile, mas não tenho certeza.

**Comment by miguelpeixe** [comment]
Fala @diraol 

Recentemente o mapbox mudou a biblioteca deles para um plugin do Leaflet.
Semana passada lançamos a adaptação das bibliotecas no [branch dev](https://github.com/cardume/mappress/tree/dev).

Dá uma olhada se o erro persiste nesse ambiente?

**Comment by diraol** [comment]
Fala @miguelpeixe ! =)
Aliás, parabéns pelo trabalho, ficou muito bom!!!! Espero poder contribuir!

Troquei o branch para o dev, agora o mapa aparece, mas os "dados" não. Só aparece o tile do fundo mesmo.

O erro agora é diferente. "Uncaught Error: Invalid GeoJSON object." e "GET http://c.tiles.mapbox.com/v3/examples.map-vyofok3q,estadaodados.reservatorios/4/5/9.grid.json 404 (Not Found)"

**Comment by miguelpeixe** [comment]
Opa, contribuições serão bem-vindas!

Não consegui visualizar o seu mapa porque os limites de navegação dele são restritos, não suporta zoom menor que 6. Nesses casos é bom adicionar uma outra layer por trás, para que o mapbox faça o "composite" e não haja problemas na navegação. Ou você pode travar a visualização usando as ferramentas do mappress para o zoom e bounds definidos (que é mais econômico).

**Comment by diraol** [comment]
Ah! Agora eu entendi como funciona e o porque não havia funcionado antes! =) Valeu pelo toque ;)

Vou ver como interagir, mas vai levar um tempinho até entender tudo e começar a colaborar rs. Mas pretendo colaborar sim!

**Comment by ericodc** [comment]
acho que vi um problema um pouco diferente, e pergunto se há alguma dependência específica, tenho o mappress funcionando bem no meu computador, mas coloquei em uma hospedagem compartilhada e no pagodabox.com, mas em ambos os casos o mapa não aparece. Nem msg de erro também.
