### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sabas** [oeco/jeo#23]
I see there aren't comments per post. They are simply hidden or disabled by the theme?

**Comment by miguelpeixe** [comment]
They are not placed on the theme. It'll be integrated on the next release!

**Comment by snpr25** [comment]
O JEO suprime a funcionalidade de visualizacao dos comentarios nas postagens do wordpress.
Para projetos participativos onde é importante coletar a percepção da massa (crowd) é essencial a possibilidade de visualização e inserção dos comentarios nos posts georreferenciados.
Se eu pude ajudar a codificar ,nos limites de minhas habilidades gostaria de contribuir.

**Comment by vjpixel** [comment]
@snpr25 we plan to make a release this week with this feature.

**Comment by miguelpeixe** [comment]
support added on 0.8.11 release
