### ISSUE TITLE
limited number of posts in map

### ISSUE THREAD

**Issue by snpr25** [oeco/jeo#32]
I am with 580 posts and only a small part are in my map.
Is there a limit? if true how do i override this limit?

**Comment by miguelpeixe** [comment]
You can use the `jeo_markers_limit` filter on the `functions.php` file from your theme to set this limit (preferably a child theme, to keep JEO files intact).

It should look something like this:

``` php
function my_markers_limit() {
  return -1; // Use -1 for unlimited;
}
add_filter('jeo_markers_limit', 'my_markers_limit');
```
