### ISSUE TITLE
how to add 'rel' to market bubble map post link?

### ISSUE THREAD

**Issue by rbrazileiro** [oeco/jeo#33]
I want to use AJAX to load post content inside index.php

**Comment by miguelpeixe** [comment]
I'm not sure what you mean by "rel" to marker bubble, but if you want to work with AJAX connected to the markers, you can start working with this:

``` javascript
jeo.markersReady(function(map) {
  var markers = map._markers;
  console.log(markers[0]); // check out the structure;
  // Start working with the markers with your code
});
```

[Some reference on the marker object](http://leafletjs.com/reference.html#marker)

**Comment by rbrazileiro** [comment]
thanks!

**Comment by miguelpeixe** [comment]
Another quick tip, if you want to pass custom meta to the properties of the marker's geojson feature, you can do that with this wordpress filter:

``` php
function my_custom_data($properties, $post) {
  // add post custom data
  $properties['my_custom_meta'] = get_post_meta($post->ID, 'my-custom-meta', true);
  // custom posts data
  if(get_post_type($post) == 'custom-post-type') {
    $properties['custom'] = get_post_meta($post->ID, 'custom-post-type-meta', true);
  }
  return $properties; 
}
add_filter('jeo_marker_data', 'my_custom_data', 10, 2);
```

This can be useful if you are working with javascript based filters using custom post data
