### ISSUE TITLE
use part of Jeo for another WP template

### ISSUE THREAD

**Issue by miguelpaz** [oeco/jeo#40]
I have a WP setup with specific purposes that also requires as a small part of it, geomapping stories. I would like to add Jeo`s mapping features. Is there a way to do that without installing the full template?

**Comment by miguelpeixe** [comment]
The whole system is located on the `inc` and `metaboxes` directory (along with the `lib` directory, with vendor libraries).

You can look at how the template uses the template functions and hooks to use maps functionalities.
