### ISSUE TITLE
JEO/servidor compartilhado e mapa

### ISSUE THREAD

**Issue by tamielbr** [oeco/jeo#43]
Eu havia re-aberto essa questão (mapa não aparece depois de instalado e configurado corretamente). mas investigando com mais calma, consigo instalar o JEO tranquilamente em máquina local, porém com o mesmo setup em servidor compartilhado, tenho problemas. O problema é no servidor compartilhado (Kinghost). O problema parece ser esse, no entanto não consigo decifrar o que pode ser (console do Firefox):

Request URL:    http://educacaoaberta.org/redefem/wp-admin/admin-ajax.php?action=map_data&map_id=18
Request Method:     GET
Status Code:    HTTP/1.1 500 Internal Server Error

**Comment by miguelpeixe** [comment]
Para analisar melhor precisamos dar uma olhada no error_log do PHP

**Comment by tamielbr** [comment]
Eu ligo o error log do PHP e ele aparece limpo, sem nenhuma referência ao site. 
Pedi aos admins que me passem outros logs (se existirem). Alguma coisa que possa ser vista via browser?

**Comment by miguelpeixe** [comment]
Provavelmente o error log está em outro lugar, erro 500 sempre retorna algo no log. Talvez busque por informações sobre onde o Kinghost armazena log de erros das contas compartilhadas

**Comment by tamielbr** [comment]
O que recebi: 

The status page does not return a valid Content-Type header:

...
text/plain
Content-type: text/plain
...

it should be

...
Content-type: text/plain
...

It affects apache but also any other front web servers. Nginx is more tolerant 
and ignores unknown / malformed headers but text/html was use instead.

Me colocaram no Nginx, resolveu. Mas pode ser um problema a ser arrumado?
