### ISSUE TITLE
Set zoom level for map in posts / pages ?

### ISSUE THREAD

**Issue by fariskassim** [oeco/jeo#46]
is there a way to set or change the zoom level of the map in the header of individual posts? i want a more zoomed out map instead of the default zoom level

![screen shot 2014-05-29 at 1 32 25 pm](https://cloud.githubusercontent.com/assets/2416787/3114410/b93d025c-e6f2-11e3-9edc-cec34bd4f022.png)

**Comment by gufalei** [comment]
Dear Fariskassin

Right bellow the geocoding feature for the post there is a field for
setting the zoom, you can use from 1 to 14 (the latest the closest zoom).
Look at the image bellow

[image: Imagem inline 2]
![Uploading image.png . . .]()

2014-05-29 2:33 GMT-03:00 fariskassim notifications@github.com:

> is there a way to set or change the zoom level of the map in the header of
> individual posts? i want a more zoomed out map instead of the default zoom
> level
> 
> [image: screen shot 2014-05-29 at 1 32 25 pm]
> https://cloud.githubusercontent.com/assets/2416787/3114410/b93d025c-e6f2-11e3-9edc-cec34bd4f022.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oeco/jeo/issues/46.

## 

Gustavo Faleiros

**Comment by fariskassim** [comment]
ah alright, thanks.

i got this done by changing the map settings in jeo.js,
which probably does the same thing.

obrigado !
