### ISSUE TITLE
Como inserir arquivos geojson como BG do Mapa

### ISSUE THREAD

**Issue by narceliodesa** [oeco/jeo#49]
Tenho arquivos geojson que gostaria que ficassem como camadas nos mapas, como proceder? 

Site: http://narceliodesa.com/cartografiasocial

**Comment by gufalei** [comment]
Não temos suporte para subir arquivos ou links geojson diretamente, as opções são gerar no próprio mapbox ou cartodb e depois inserir a API (ID no mapbox ou URL no CartoDB)

Não sei se conhece a outra plataforma nossa, Mapas Coletivos , que permite importação de geojson

http://www.mapascoletivos.com.br/
