### ISSUE TITLE
how to load featured image in bubble-marker?

### ISSUE THREAD

**Issue by doutorsocrates** [oeco/jeo#51]
I try to insert content-marker-bubble.php with:
the_post_thumbnail();
but it does not recognize.
Is there another solution?

**Comment by miguelpeixe** [comment]
It's supposed to work. Can you paste all the code on content-marker-bubble.php?

As you can see in [this child theme](https://github.com/cardume/arteforadomuseu/blob/master/content-marker-bubble.php), the marker bubble content have a thumbnail and [its working](http://arteforadomuseu.com.br)

**UPDATE**
What you might be experiecing is cache delay. If you add random content to the content marker bubble, does it immediately appers?

**Comment by doutorsocrates** [comment]
<?php
/*
- Mousehover bubble content
  */
  ?>
  <small><?php echo get_the_date(_x('m/d/Y', 'map bubble date format', 'jeo')); ?></small>
  <h4><?php the_title(); ?></h4>
  <?php 
  if ( has_post_thumbnail() ) { 
  the_post_thumbnail();
  } 
  ?>

**Comment by miguelpeixe** [comment]
The code looks ok.

The post bubble content is stored in it's GeoJSON cache. Have you tried clearing the GeoJSON cache on the admin bar and clearing your browser's cache after updating this code?

**Comment by doutorsocrates** [comment]
bingo. I had to clear the cache for 3 or 4 times and it worked.

thanks very much

**Comment by miguelpeixe** [comment]
You don't need to purge this cache 3 or 4 times. It might be the combination of caching features that had you struggle on this. Since the markers request can get pretty big there's also a [transient cache](http://codex.wordpress.org/Transients_API) that stores every marker request for 10 minutes. This cache can be disabled by adding this code to your functions.php:

``` php
function my_markers_enable_transient() {
  return false;
}
add_filter('jeo_markers_enable_transient', 'my_markers_enable_transient');
```
