### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by DavidLemayian** [oeco/jeo#52]
Hi,

I would like to import data on a CSV to a JEO themed Wordpress instance. Any way to do this easily and efficiently?

Cheers,
David.

**Comment by gufalei** [comment]
Hey David

If you want to import data as posts, we recommend a plug in for CSV import, it usually works well

If you want to transform this points in on layer of static data, you can render the data with MapBox or Carto DB and publish as a map using JEO .

Does it work

**Comment by DavidLemayian** [comment]
Hey @gufalei. Thanks for the reply. I indeed used a CSV import plugin. I have also added the related fields to `geocode_address`, `geocode_longitude` and `geocode_latitude`.

With this achieved, how would I have the `geocode_*` processed by JEO to display on the map as with a normal post added through the dashboard?
