### ISSUE TITLE
Problem with add/edit post and theme code

### ISSUE THREAD

**Issue by kingstakh** [oeco/jeo#59]
Use Wordpress 3.9.2 and last JEO beta version.
When I add new post to map on frontend map is not show. Post show in "Latest articles" but on map don't. When I click to read more, on single page marker show. If I change "Featured map" on frontend than new post marker now show, when back to previous "Featured map" maker don't show.

If I change category post or marker image on frontend maker display without changes with previous marker image and category name on map, but in "Latest articles" category changing. If create new post all changes applied to new, but old post stay without changes.

And if I change something in theme code, example change infobubble in content-marker-bubble.php, all old post markers have previous edition, but new marker have infobubble with new edition. And on frontend map have two infobubble types, old post with old edition - new post with new edition content-marker-bubble.php.

It's not cache of my browser, try see changes on other devices and from other locations my friends.

After 20-30 min after changer if renew page all stay good.  Looks like engine theme cache, but how fix that?

**Comment by miguelpeixe** [comment]
Hi @kingstakh 

Yes, this is an issue with our cache system. Since marker rendering can get very big we have several caches working to minimize delays. You can clear the geojson cache to force the data rebuild. This button is available on your admin bar (fixed on the top of the page).
