### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by tamielbr** [oeco/jeo#61]
O mapa não aparece no site com www e sem www no endereço. Ou seja, aparece em mamu.net.br, mas não em www.mamu.net.br. Isso parece estar alinhado ao endereço compatível com o de instalação (nas preferências) do WP. Parece que a chamada do mapa pega o endereço absoluto e não relativo (/mamu.net.br, ao invés de http://mamu.net.br ou http://www.mamu.net.br).

Erro: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://mamu.net.br/wp-admin/admin-ajax.php?action=map_data&map_id=9. This can be fixed by moving the resource to the same domain or enabling CORS."

**Comment by tamielbr** [comment]
Não resolve: https://github.com/jacopotarantino/WordPress-Cross-Domain-Plugin

**Comment by tamielbr** [comment]
Uma solução (que parece precária) é editar o wp-config.php e dar um hardcode com dois sites diferentes:
define('WP_HOME','http://mamu.net.br');
define('WP_SITEURL','http://www.mamu.net.br');

**Comment by miguelpeixe** [comment]
Oi @tamielbr 

A melhor saída é criar um redirecionamento no seu DNS para adicionar ou remover o prefixo www. Geralmente os paineis de controle de hospedagem tem essa opção.

**Comment by tamielbr** [comment]
Brinquei com DNS bastante, mas nada resolve. Vou ver se o host tem alguma sugestão.

**Comment by tamielbr** [comment]
Resolvido no setup do DNS.
