### ISSUE TITLE
error message  when embed tool is enabled 

### ISSUE THREAD

**Issue by mawy75** [oeco/jeo#65]
Hi there! Please, can you help me?
I'm trying to enable the embed tool. When i click on "Check it out" from my dashboard or on the direct link to the page that could be generated (mysite/share/?), my hosting service (Bluehost) gives the error message "404 Error File Not Found The page you are looking for might have been removed, 
had its name changed, or is temporarily unavailable."

I've tried with Altervista and it doesn't happen.
Thanks!

**Comment by miguelpeixe** [comment]
Hi @mawy75 

The embed tool only works with custom permalinks. What's your permalink settings now?

**Comment by mawy75** [comment]
Now it works perfectly.
I was with default option, no problem with "post name" one.
Thank you very much!

**Comment by mayatavora** [comment]
Oi , coloquei o meu em custom permalinks. E o Botão Share a map, não funciona. Ja preenchi o campo vazio,  do custom permalinks, com /%category%/%postname% ja tentei colocar so %postname%
E nao consegui fazer funcionar o share a map

Ao clicar da um erro 404, meu provedor e locaweb.
