### ISSUE TITLE
Using mapbox on JEO

### ISSUE THREAD

**Issue by tamielbr** [oeco/jeo#66]
I am trying to add a Mapbox layer (not data, just the tiles). I add the ID from mapbox to the field, but nothing shows. I couldn't find any orientation (on the previous issues). I also put the URL, but nothing shows. 

I am the process of writing a small manual for users of JEO, and this would be helpful information!

![screen shot 2015-02-03 at 10 56 31](https://cloud.githubusercontent.com/assets/3904166/6025927/68af8ba0-ab93-11e4-8889-11ef8a02206e.png)

**Comment by michelmetran** [comment]
I'm with the same doubt.
I have a project in MapBox, put the Map ID in JEO and nothing is showed.
I do not have any datasets in MapBox. Its necessary pay for import shapefiles (my need).
Maybe JEO not support projects, accepting only datasets.... i will keeping trying... very nice theme!, I want use this!!

**Comment by gufalei** [comment]
Hey guys sorry for late response. This is kind of odd . We know the pin points or the kml, gpx files uploaded directly in MapBox will not work. But any other layers hosted as data , coming directly from Tile Mill, or full maps created as projects would be showing up within JEO. Can you please try using this ID to see if the data is showing:  infoamazonia.deforestation-sad

And one detail, is the account you are using at MapBox free or paid? I am wondering if this could be their API problem

**Comment by michelmetran** [comment]
Gustavo,
Now I understand. I was using mapbox with KML imported .... i don´t use tile mill... I don't knowed about this... 
Trying many diferent options and I decide use CartoDB... best meets my needs ....
I´m using a free MapBox... and, testing the 'infoamazonia.deforestation-sad', it´s ok! It´s showing normaly....

**Comment by gufalei** [comment]
good @michelmetran let me know if you find any problems
you know with CartoDB you have to use the js url, i mean the json link

@tamielbr this answer help in any way? or still having the problem?

**Comment by tamielbr** [comment]
Sorry for the delay. This works, thank you! Also works with the solution presented in #74.

**Comment by miguelpeixe** [comment]
Fixed on b5472b764207e11ea6b39cba2c16dfb0c95eec74

Available on [version 1.0.1](https://github.com/oeco/jeo/releases/tag/v1.0.1)
You can add MapBox access token through JEO Settings, on the dashboard.
