### ISSUE TITLE
Mapbox layers will not work from multiple accounts

### ISSUE THREAD

**Issue by brownwing** [oeco/jeo#74]
using mapbox map ids from multiple accounts results in blank maps - or in only one map layer being present.

eg - sharkmouse.345a6d9a provides a consistent base layer

but sandybell.5dcce76a does not show up at all

**Comment by brownwing** [comment]
Mapbox confirms that this is because old accounts have the API v 3 grandfathered in, but newer accounts have to use V4, and hence an API key

**Comment by brownwing** [comment]
as a work around you can serve mapbox maps as tiles, using the API key in this configuration

http://api.tiles.mapbox.com/v4/{mapID}/{z}/{x}/{y}.png?access_token={your public key}

**Comment by miguelpeixe** [comment]
hello @brownwing 

I just published a new release on JEO 1.0 with the fix. You can add the access token through JEO settings, on the dashboard.

b5472b764207e11ea6b39cba2c16dfb0c95eec74

thanks for reporting!
