### ISSUE TITLE
GeoJOSN export limited to 100 items

### ISSUE THREAD

**Issue by vgeorge** [oeco/jeo#78]
See this [example](http://infoamazonia.org/news/?infoamazonia_filter_=1&infoamazonia_filter_s=&infoamazonia_filter_category%5B%5D=142&infoamazonia_filter_date_start=&infoamazonia_filter_date_end=#!/map=49&story=post-13990&loc=-5.615985819155327,-61.06201171875,5). Only a 100 ot total items are returned.

**Comment by vgeorge** [comment]
Date filter seems not to be working, too.

**Comment by miguelpeixe** [comment]
Use `X-Total-Count` header value with `paged` GET parameter for pagination

**Comment by miguelpeixe** [comment]
Use another issue for the date filter
